apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tidb-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tidb-builder
  serviceName: tidb-builder
  template:
    metadata:
      labels:
        app: tidb-builder
    spec:
      containers:
      - name: builder
        image: hub.pingcap.com/pingcap/tidb-builder
        command: ["tail", "-f", "/dev/null"]
        volumeMounts:
        - name: varrun
          mountPath: /var/run
      - name: dind
        image: hub.pingcap.com/pingcap/docker:dind
        command:
        - dockerd
        - --host=unix:///var/run/docker.sock
        volumeMounts:
        - name: varrun
          mountPath: /var/run
        securityContext:
          privileged: true
      volumes:
      - name: varrun
        emptyDir: {}
